/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Product_Abstraccion.Ficha;
import Singelton.Tablero;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author david
 */
public class Vista extends javax.swing.JFrame {

    private String turno;
    private Tablero tablero;
    private ArrayList<JLabel> Casillas;

    public void setTurno(String turno) {
        this.turno = turno;
    }

    public Vista(Tablero tablero) {
        this.turno = "Blanco";
        this.tablero = tablero;
        initComponents();
        setLocationRelativeTo(null);
        Casillas = new ArrayList();
        Casillas.add(FichaCasilla0A);
        Casillas.add(FichaCasilla0B);
        Casillas.add(FichaCasilla0C);
        Casillas.add(FichaCasilla0D);
        Casillas.add(FichaCasilla0E);
        Casillas.add(FichaCasilla0F);
        Casillas.add(FichaCasilla0G);
        Casillas.add(FichaCasilla0H);
        Casillas.add(FichaCasilla1A);
        Casillas.add(FichaCasilla1B);
        Casillas.add(FichaCasilla1C);
        Casillas.add(FichaCasilla1D);
        Casillas.add(FichaCasilla1E);
        Casillas.add(FichaCasilla1F);
        Casillas.add(FichaCasilla1G);
        Casillas.add(FichaCasilla1H);
        Casillas.add(FichaCasilla2A);
        Casillas.add(FichaCasilla2B);
        Casillas.add(FichaCasilla2C);
        Casillas.add(FichaCasilla2D);
        Casillas.add(FichaCasilla2E);
        Casillas.add(FichaCasilla2F);
        Casillas.add(FichaCasilla2G);
        Casillas.add(FichaCasilla2H);
        Casillas.add(FichaCasilla3A);
        Casillas.add(FichaCasilla3B);
        Casillas.add(FichaCasilla3C);
        Casillas.add(FichaCasilla3D);
        Casillas.add(FichaCasilla3E);
        Casillas.add(FichaCasilla3F);
        Casillas.add(FichaCasilla3G);
        Casillas.add(FichaCasilla3H);
        Casillas.add(FichaCasilla4A);
        Casillas.add(FichaCasilla4B);
        Casillas.add(FichaCasilla4C);
        Casillas.add(FichaCasilla4D);
        Casillas.add(FichaCasilla4E);
        Casillas.add(FichaCasilla4F);
        Casillas.add(FichaCasilla4G);
        Casillas.add(FichaCasilla4H);
        Casillas.add(FichaCasilla5A);
        Casillas.add(FichaCasilla5B);
        Casillas.add(FichaCasilla5C);
        Casillas.add(FichaCasilla5D);
        Casillas.add(FichaCasilla5E);
        Casillas.add(FichaCasilla5F);
        Casillas.add(FichaCasilla5G);
        Casillas.add(FichaCasilla5H);
        Casillas.add(FichaCasilla6A);
        Casillas.add(FichaCasilla6B);
        Casillas.add(FichaCasilla6C);
        Casillas.add(FichaCasilla6D);
        Casillas.add(FichaCasilla6E);
        Casillas.add(FichaCasilla6F);
        Casillas.add(FichaCasilla6G);
        Casillas.add(FichaCasilla6H);
        Casillas.add(FichaCasilla7A);
        Casillas.add(FichaCasilla7B);
        Casillas.add(FichaCasilla7C);
        Casillas.add(FichaCasilla7D);
        Casillas.add(FichaCasilla7E);
        Casillas.add(FichaCasilla7F);
        Casillas.add(FichaCasilla7G);
        Casillas.add(FichaCasilla7H);
        JugadaBlanco();

        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTablero = new javax.swing.JPanel();
        FichaCasilla0A = new javax.swing.JLabel();
        FichaCasilla0B = new javax.swing.JLabel();
        FichaCasilla0C = new javax.swing.JLabel();
        FichaCasilla0D = new javax.swing.JLabel();
        FichaCasilla0E = new javax.swing.JLabel();
        FichaCasilla0F = new javax.swing.JLabel();
        FichaCasilla0G = new javax.swing.JLabel();
        FichaCasilla0H = new javax.swing.JLabel();
        FichaCasilla1A = new javax.swing.JLabel();
        FichaCasilla1B = new javax.swing.JLabel();
        FichaCasilla1C = new javax.swing.JLabel();
        FichaCasilla1D = new javax.swing.JLabel();
        FichaCasilla1E = new javax.swing.JLabel();
        FichaCasilla1F = new javax.swing.JLabel();
        FichaCasilla1G = new javax.swing.JLabel();
        FichaCasilla1H = new javax.swing.JLabel();
        FichaCasilla2A = new javax.swing.JLabel();
        FichaCasilla2B = new javax.swing.JLabel();
        FichaCasilla2C = new javax.swing.JLabel();
        FichaCasilla2D = new javax.swing.JLabel();
        FichaCasilla2E = new javax.swing.JLabel();
        FichaCasilla2F = new javax.swing.JLabel();
        FichaCasilla2G = new javax.swing.JLabel();
        FichaCasilla2H = new javax.swing.JLabel();
        FichaCasilla3A = new javax.swing.JLabel();
        FichaCasilla3B = new javax.swing.JLabel();
        FichaCasilla3C = new javax.swing.JLabel();
        FichaCasilla3D = new javax.swing.JLabel();
        FichaCasilla3E = new javax.swing.JLabel();
        FichaCasilla3F = new javax.swing.JLabel();
        FichaCasilla3G = new javax.swing.JLabel();
        FichaCasilla3H = new javax.swing.JLabel();
        FichaCasilla4A = new javax.swing.JLabel();
        FichaCasilla4B = new javax.swing.JLabel();
        FichaCasilla4C = new javax.swing.JLabel();
        FichaCasilla4D = new javax.swing.JLabel();
        FichaCasilla4E = new javax.swing.JLabel();
        FichaCasilla4F = new javax.swing.JLabel();
        FichaCasilla4G = new javax.swing.JLabel();
        FichaCasilla4H = new javax.swing.JLabel();
        FichaCasilla5A = new javax.swing.JLabel();
        FichaCasilla5B = new javax.swing.JLabel();
        FichaCasilla5C = new javax.swing.JLabel();
        FichaCasilla5D = new javax.swing.JLabel();
        FichaCasilla5E = new javax.swing.JLabel();
        FichaCasilla5F = new javax.swing.JLabel();
        FichaCasilla5G = new javax.swing.JLabel();
        FichaCasilla5H = new javax.swing.JLabel();
        FichaCasilla6A = new javax.swing.JLabel();
        FichaCasilla6B = new javax.swing.JLabel();
        FichaCasilla6C = new javax.swing.JLabel();
        FichaCasilla6D = new javax.swing.JLabel();
        FichaCasilla6E = new javax.swing.JLabel();
        FichaCasilla6F = new javax.swing.JLabel();
        FichaCasilla6G = new javax.swing.JLabel();
        FichaCasilla6H = new javax.swing.JLabel();
        FichaCasilla7A = new javax.swing.JLabel();
        FichaCasilla7B = new javax.swing.JLabel();
        FichaCasilla7C = new javax.swing.JLabel();
        FichaCasilla7D = new javax.swing.JLabel();
        FichaCasilla7E = new javax.swing.JLabel();
        FichaCasilla7F = new javax.swing.JLabel();
        FichaCasilla7G = new javax.swing.JLabel();
        FichaCasilla7H = new javax.swing.JLabel();
        Casilla0A = new javax.swing.JLabel();
        Casilla0B = new javax.swing.JLabel();
        Casilla0C = new javax.swing.JLabel();
        Casilla0D = new javax.swing.JLabel();
        Casilla0E = new javax.swing.JLabel();
        Casilla0F = new javax.swing.JLabel();
        Casilla0G = new javax.swing.JLabel();
        Casilla0H = new javax.swing.JLabel();
        Casilla1A = new javax.swing.JLabel();
        Casilla1B = new javax.swing.JLabel();
        Casilla1C = new javax.swing.JLabel();
        Casilla1D = new javax.swing.JLabel();
        Casilla1E = new javax.swing.JLabel();
        Casilla1F = new javax.swing.JLabel();
        Casilla1G = new javax.swing.JLabel();
        Casilla1H = new javax.swing.JLabel();
        Casilla2A = new javax.swing.JLabel();
        Casilla2B = new javax.swing.JLabel();
        Casilla2C = new javax.swing.JLabel();
        Casilla2D = new javax.swing.JLabel();
        Casilla2E = new javax.swing.JLabel();
        Casilla2F = new javax.swing.JLabel();
        Casilla2G = new javax.swing.JLabel();
        Casilla2H = new javax.swing.JLabel();
        Casilla3A = new javax.swing.JLabel();
        Casilla3B = new javax.swing.JLabel();
        Casilla4C = new javax.swing.JLabel();
        Casilla3D = new javax.swing.JLabel();
        Casilla3E = new javax.swing.JLabel();
        Casilla3F = new javax.swing.JLabel();
        Casilla3G = new javax.swing.JLabel();
        Casilla3H = new javax.swing.JLabel();
        Casilla4A = new javax.swing.JLabel();
        Casilla4B = new javax.swing.JLabel();
        Casilla5C = new javax.swing.JLabel();
        Casilla4D = new javax.swing.JLabel();
        Casilla4E = new javax.swing.JLabel();
        Casilla4F = new javax.swing.JLabel();
        Casilla4G = new javax.swing.JLabel();
        Casilla4H = new javax.swing.JLabel();
        Casilla5A = new javax.swing.JLabel();
        Casilla5B = new javax.swing.JLabel();
        Casilla6C = new javax.swing.JLabel();
        Casilla5D = new javax.swing.JLabel();
        Casilla5E = new javax.swing.JLabel();
        Casilla5F = new javax.swing.JLabel();
        Casilla5G = new javax.swing.JLabel();
        Casilla5H = new javax.swing.JLabel();
        Casilla6A = new javax.swing.JLabel();
        Casilla6B = new javax.swing.JLabel();
        Casilla7C = new javax.swing.JLabel();
        Casilla6D = new javax.swing.JLabel();
        Casilla6E = new javax.swing.JLabel();
        Casilla6F = new javax.swing.JLabel();
        Casilla6G = new javax.swing.JLabel();
        Casilla6H = new javax.swing.JLabel();
        Casilla7A = new javax.swing.JLabel();
        Casilla7B = new javax.swing.JLabel();
        Casilla8C = new javax.swing.JLabel();
        Casilla7D = new javax.swing.JLabel();
        Casilla7E = new javax.swing.JLabel();
        Casilla7F = new javax.swing.JLabel();
        Casilla7G = new javax.swing.JLabel();
        Casilla7H = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelTablero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FichaCasilla0A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TorreNegro.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla0A, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        FichaCasilla0B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CaballoNegro.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla0B, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 50, 50));

        FichaCasilla0C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AlfilNegro.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla0C, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 50, 50));

        FichaCasilla0D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ReyNegro.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla0D, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 50, 50));

        FichaCasilla0E.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ReinaNegro.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla0E, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 50, 50));

        FichaCasilla0F.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AlfilNegro.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla0F, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 50, 50));

        FichaCasilla0G.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CaballoNegro.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla0G, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 50, 50));

        FichaCasilla0H.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TorreNegro.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla0H, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 50, 50));

        FichaCasilla1A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PeonNegro.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla1A, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 50));

        FichaCasilla1B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PeonNegro.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla1B, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 50, 50));

        FichaCasilla1C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PeonNegro.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla1C, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 50, 50));

        FichaCasilla1D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PeonNegro.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla1D, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 50, 50));

        FichaCasilla1E.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PeonNegro.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla1E, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 50, 50));

        FichaCasilla1F.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PeonNegro.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla1F, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 50, 50));

        FichaCasilla1G.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PeonNegro.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla1G, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 50, 50));

        FichaCasilla1H.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PeonNegro.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla1H, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 50, 50));
        jPanelTablero.add(FichaCasilla2A, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 50, 50));
        jPanelTablero.add(FichaCasilla2B, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 50, 50));
        jPanelTablero.add(FichaCasilla2C, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 50, 50));
        jPanelTablero.add(FichaCasilla2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 50, 50));
        jPanelTablero.add(FichaCasilla2E, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 50, 50));
        jPanelTablero.add(FichaCasilla2F, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 50, 50));
        jPanelTablero.add(FichaCasilla2G, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 50, 50));
        jPanelTablero.add(FichaCasilla2H, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 50, 50));
        jPanelTablero.add(FichaCasilla3A, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 50, 50));
        jPanelTablero.add(FichaCasilla3B, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 50, 50));
        jPanelTablero.add(FichaCasilla3C, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 50, 50));
        jPanelTablero.add(FichaCasilla3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 50, 50));
        jPanelTablero.add(FichaCasilla3E, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 50, 50));
        jPanelTablero.add(FichaCasilla3F, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 50, 50));
        jPanelTablero.add(FichaCasilla3G, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 50, 50));
        jPanelTablero.add(FichaCasilla3H, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 50, 50));
        jPanelTablero.add(FichaCasilla4A, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 50, 50));
        jPanelTablero.add(FichaCasilla4B, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 50, 50));
        jPanelTablero.add(FichaCasilla4C, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 50, 50));
        jPanelTablero.add(FichaCasilla4D, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 50, 50));
        jPanelTablero.add(FichaCasilla4E, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 50, 50));
        jPanelTablero.add(FichaCasilla4F, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 50, 50));
        jPanelTablero.add(FichaCasilla4G, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 50, 50));
        jPanelTablero.add(FichaCasilla4H, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 50, 50));
        jPanelTablero.add(FichaCasilla5A, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 50, 50));
        jPanelTablero.add(FichaCasilla5B, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 50, 50));
        jPanelTablero.add(FichaCasilla5C, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 50, 50));
        jPanelTablero.add(FichaCasilla5D, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 50, 50));
        jPanelTablero.add(FichaCasilla5E, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 50, 50));
        jPanelTablero.add(FichaCasilla5F, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 50, 50));
        jPanelTablero.add(FichaCasilla5G, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 50, 50));
        jPanelTablero.add(FichaCasilla5H, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 50, 50));

        FichaCasilla6A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PeonBlanco.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla6A, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 50, 50));

        FichaCasilla6B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PeonBlanco.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla6B, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 50, 50));

        FichaCasilla6C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PeonBlanco.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla6C, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 50, 50));

        FichaCasilla6D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PeonBlanco.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla6D, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 50, 50));

        FichaCasilla6E.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PeonBlanco.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla6E, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 50, 50));

        FichaCasilla6F.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PeonBlanco.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla6F, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 50, 50));

        FichaCasilla6G.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PeonBlanco.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla6G, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 50, 50));

        FichaCasilla6H.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PeonBlanco.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla6H, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 50, 50));

        FichaCasilla7A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TorreBlanco.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla7A, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 50, 50));

        FichaCasilla7B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CaballoBlanco.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla7B, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 50, 50));

        FichaCasilla7C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AlfilBlanco.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla7C, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 50, 50));

        FichaCasilla7D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ReinaBlanco.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla7D, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 50, 50));

        FichaCasilla7E.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ReyBlanco.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla7E, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 50, 50));

        FichaCasilla7F.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AlfilBlanco.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla7F, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 50, 50));

        FichaCasilla7G.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CaballoBlanco.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla7G, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 50, 50));

        FichaCasilla7H.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TorreBlanco.png"))); // NOI18N
        jPanelTablero.add(FichaCasilla7H, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 50, 50));

        Casilla0A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla0A, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        Casilla0B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla0B, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 50, 50));

        Casilla0C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla0C, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 50, 50));

        Casilla0D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla0D, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 50, 50));

        Casilla0E.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla0E, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 50, 50));

        Casilla0F.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla0F, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 50, 50));

        Casilla0G.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla0G, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 50, 50));

        Casilla0H.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla0H, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 50, 50));

        Casilla1A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla1A, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 50));

        Casilla1B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla1B, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 50, 50));

        Casilla1C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla1C, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 50, 50));

        Casilla1D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla1D, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 50, 50));

        Casilla1E.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla1E, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 50, 50));

        Casilla1F.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla1F, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 50, 50));

        Casilla1G.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla1G, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 50, 50));

        Casilla1H.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla1H, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 50, 50));

        Casilla2A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla2A, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 50, 50));

        Casilla2B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla2B, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 50, 50));

        Casilla2C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla2C, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 50, 50));

        Casilla2D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 50, 50));

        Casilla2E.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla2E, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 50, 50));

        Casilla2F.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla2F, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 50, 50));

        Casilla2G.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla2G, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 50, 50));

        Casilla2H.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla2H, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 50, 50));

        Casilla3A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla3A, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 50, 50));

        Casilla3B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla3B, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 50, 50));

        Casilla4C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla4C, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 50, 50));

        Casilla3D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 50, 50));

        Casilla3E.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla3E, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 50, 50));

        Casilla3F.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla3F, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 50, 50));

        Casilla3G.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla3G, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 50, 50));

        Casilla3H.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla3H, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 50, 50));

        Casilla4A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla4A, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 50, 50));

        Casilla4B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla4B, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 50, 50));

        Casilla5C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla5C, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 50, 50));

        Casilla4D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla4D, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 50, 50));

        Casilla4E.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla4E, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 50, 50));

        Casilla4F.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla4F, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 50, 50));

        Casilla4G.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla4G, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 50, 50));

        Casilla4H.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla4H, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 50, 50));

        Casilla5A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla5A, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 50, 50));

        Casilla5B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla5B, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 50, 50));

        Casilla6C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla6C, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 50, 50));

        Casilla5D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla5D, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 50, 50));

        Casilla5E.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla5E, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 50, 50));

        Casilla5F.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla5F, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 50, 50));

        Casilla5G.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla5G, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 50, 50));

        Casilla5H.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla5H, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 50, 50));

        Casilla6A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla6A, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 50, 50));

        Casilla6B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla6B, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 50, 50));

        Casilla7C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla7C, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 50, 50));

        Casilla6D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla6D, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 50, 50));

        Casilla6E.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla6E, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 50, 50));

        Casilla6F.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla6F, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 50, 50));

        Casilla6G.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla6G, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 50, 50));

        Casilla6H.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla6H, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 50, 50));

        Casilla7A.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla7A, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 50, 50));

        Casilla7B.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla7B, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 50, 50));

        Casilla8C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla8C, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 50, 50));

        Casilla7D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla7D, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 50, 50));

        Casilla7E.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla7E, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 50, 50));

        Casilla7F.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla7F, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 50, 50));

        Casilla7G.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown dark_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla7G, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 50, 50));

        Casilla7H.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/square brown light_png_shadow_1024px.png"))); // NOI18N
        jPanelTablero.add(Casilla7H, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 50, 50));

        getContentPane().add(jPanelTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Casilla0A;
    public javax.swing.JLabel Casilla0B;
    public javax.swing.JLabel Casilla0C;
    public javax.swing.JLabel Casilla0D;
    public javax.swing.JLabel Casilla0E;
    public javax.swing.JLabel Casilla0F;
    public javax.swing.JLabel Casilla0G;
    public javax.swing.JLabel Casilla0H;
    public javax.swing.JLabel Casilla1A;
    public javax.swing.JLabel Casilla1B;
    public javax.swing.JLabel Casilla1C;
    public javax.swing.JLabel Casilla1D;
    public javax.swing.JLabel Casilla1E;
    public javax.swing.JLabel Casilla1F;
    public javax.swing.JLabel Casilla1G;
    public javax.swing.JLabel Casilla1H;
    public javax.swing.JLabel Casilla2A;
    public javax.swing.JLabel Casilla2B;
    public javax.swing.JLabel Casilla2C;
    public javax.swing.JLabel Casilla2D;
    public javax.swing.JLabel Casilla2E;
    public javax.swing.JLabel Casilla2F;
    public javax.swing.JLabel Casilla2G;
    public javax.swing.JLabel Casilla2H;
    public javax.swing.JLabel Casilla3A;
    public javax.swing.JLabel Casilla3B;
    public javax.swing.JLabel Casilla3D;
    public javax.swing.JLabel Casilla3E;
    public javax.swing.JLabel Casilla3F;
    public javax.swing.JLabel Casilla3G;
    public javax.swing.JLabel Casilla3H;
    public javax.swing.JLabel Casilla4A;
    public javax.swing.JLabel Casilla4B;
    public javax.swing.JLabel Casilla4C;
    public javax.swing.JLabel Casilla4D;
    public javax.swing.JLabel Casilla4E;
    public javax.swing.JLabel Casilla4F;
    public javax.swing.JLabel Casilla4G;
    public javax.swing.JLabel Casilla4H;
    public javax.swing.JLabel Casilla5A;
    public javax.swing.JLabel Casilla5B;
    public javax.swing.JLabel Casilla5C;
    public javax.swing.JLabel Casilla5D;
    public javax.swing.JLabel Casilla5E;
    public javax.swing.JLabel Casilla5F;
    public javax.swing.JLabel Casilla5G;
    public javax.swing.JLabel Casilla5H;
    public javax.swing.JLabel Casilla6A;
    public javax.swing.JLabel Casilla6B;
    public javax.swing.JLabel Casilla6C;
    public javax.swing.JLabel Casilla6D;
    public javax.swing.JLabel Casilla6E;
    public javax.swing.JLabel Casilla6F;
    public javax.swing.JLabel Casilla6G;
    public javax.swing.JLabel Casilla6H;
    public javax.swing.JLabel Casilla7A;
    public javax.swing.JLabel Casilla7B;
    public javax.swing.JLabel Casilla7C;
    public javax.swing.JLabel Casilla7D;
    public javax.swing.JLabel Casilla7E;
    public javax.swing.JLabel Casilla7F;
    public javax.swing.JLabel Casilla7G;
    public javax.swing.JLabel Casilla7H;
    public javax.swing.JLabel Casilla8C;
    public javax.swing.JLabel FichaCasilla0A;
    public javax.swing.JLabel FichaCasilla0B;
    public javax.swing.JLabel FichaCasilla0C;
    public javax.swing.JLabel FichaCasilla0D;
    public javax.swing.JLabel FichaCasilla0E;
    public javax.swing.JLabel FichaCasilla0F;
    public javax.swing.JLabel FichaCasilla0G;
    public javax.swing.JLabel FichaCasilla0H;
    public javax.swing.JLabel FichaCasilla1A;
    public javax.swing.JLabel FichaCasilla1B;
    public javax.swing.JLabel FichaCasilla1C;
    public javax.swing.JLabel FichaCasilla1D;
    public javax.swing.JLabel FichaCasilla1E;
    public javax.swing.JLabel FichaCasilla1F;
    public javax.swing.JLabel FichaCasilla1G;
    public javax.swing.JLabel FichaCasilla1H;
    public javax.swing.JLabel FichaCasilla2A;
    public javax.swing.JLabel FichaCasilla2B;
    public javax.swing.JLabel FichaCasilla2C;
    public javax.swing.JLabel FichaCasilla2D;
    public javax.swing.JLabel FichaCasilla2E;
    public javax.swing.JLabel FichaCasilla2F;
    public javax.swing.JLabel FichaCasilla2G;
    public javax.swing.JLabel FichaCasilla2H;
    public javax.swing.JLabel FichaCasilla3A;
    public javax.swing.JLabel FichaCasilla3B;
    public javax.swing.JLabel FichaCasilla3C;
    public javax.swing.JLabel FichaCasilla3D;
    public javax.swing.JLabel FichaCasilla3E;
    public javax.swing.JLabel FichaCasilla3F;
    public javax.swing.JLabel FichaCasilla3G;
    public javax.swing.JLabel FichaCasilla3H;
    public javax.swing.JLabel FichaCasilla4A;
    public javax.swing.JLabel FichaCasilla4B;
    public javax.swing.JLabel FichaCasilla4C;
    public javax.swing.JLabel FichaCasilla4D;
    public javax.swing.JLabel FichaCasilla4E;
    public javax.swing.JLabel FichaCasilla4F;
    public javax.swing.JLabel FichaCasilla4G;
    public javax.swing.JLabel FichaCasilla4H;
    public javax.swing.JLabel FichaCasilla5A;
    public javax.swing.JLabel FichaCasilla5B;
    public javax.swing.JLabel FichaCasilla5C;
    public javax.swing.JLabel FichaCasilla5D;
    public javax.swing.JLabel FichaCasilla5E;
    public javax.swing.JLabel FichaCasilla5F;
    public javax.swing.JLabel FichaCasilla5G;
    public javax.swing.JLabel FichaCasilla5H;
    public javax.swing.JLabel FichaCasilla6A;
    public javax.swing.JLabel FichaCasilla6B;
    public javax.swing.JLabel FichaCasilla6C;
    public javax.swing.JLabel FichaCasilla6D;
    public javax.swing.JLabel FichaCasilla6E;
    public javax.swing.JLabel FichaCasilla6F;
    public javax.swing.JLabel FichaCasilla6G;
    public javax.swing.JLabel FichaCasilla6H;
    public javax.swing.JLabel FichaCasilla7A;
    public javax.swing.JLabel FichaCasilla7B;
    public javax.swing.JLabel FichaCasilla7C;
    public javax.swing.JLabel FichaCasilla7D;
    public javax.swing.JLabel FichaCasilla7E;
    public javax.swing.JLabel FichaCasilla7F;
    public javax.swing.JLabel FichaCasilla7G;
    public javax.swing.JLabel FichaCasilla7H;
    public javax.swing.JPanel jPanelTablero;
    // End of variables declaration//GEN-END:variables

    public void JugadaBlanco() {
        JOptionPane.showMessageDialog(null, "Turno del jugador Blanco");
        for (JLabel Casilla : Casillas) {
            if (Casilla.getIcon() != null) {
                Casilla.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        if (Casilla.getBorder() == null) {
                            for (Ficha ficha : tablero.getFichasBlancas()) {
                                if (Casilla.getIcon().toString().equals(new javax.swing.ImageIcon(getClass().getResource(ficha.getImagen())).toString())) {
                                    Casilla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 41)));
                                } else {

                                }
                            }
                        } else if (Casilla.getBorder() != null) {
                            Casilla.setBorder(null);
                        }
                    }
                });
                Casilla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            }
        }
    }
    
    public void JugadaNegro() {
        JOptionPane.showMessageDialog(null, "Turno del jugador Negro");
        for (JLabel Casilla : Casillas) {
            if (Casilla.getIcon() != null) {
                Casilla.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        if (Casilla.getBorder() == null) {
                            for (Ficha ficha : tablero.getFichasNegras()) {
                                if (Casilla.getIcon().toString().equals(new javax.swing.ImageIcon(getClass().getResource(ficha.getImagen())).toString())) {
                                    Casilla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 41)));
                                } else {

                                }
                            }
                        } else if (Casilla.getBorder() != null) {
                            Casilla.setBorder(null);
                            JugadaBlanco();
                        }
                    }
                });
                Casilla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            }
        }
    }
}
