/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PracticaFlyweight;

import Contexto.Pelota_Contexto;
import FlyWeight.TipoPelota_FlyWeight;
import FlyWeight_Factory.Fabrica_PelotaFlyWeight;
import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;

/**
 *
 * @author david
 */
public class MostrarPelotas extends javax.swing.JFrame {

    private ArrayList<Pelota_Contexto> pelotas = new ArrayList();

    /**
     * Creates new form PracticaFlyweight
     */
    public MostrarPelotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void mostrarPelota(int x, int y, String name, Color color, String descripcion) {
        TipoPelota_FlyWeight tipo_pelota = Fabrica_PelotaFlyWeight.getTipoPelota(name, color, descripcion);
        Pelota_Contexto pelota = new Pelota_Contexto(x, y, tipo_pelota);
        pelotas.add(pelota);
    }

    @Override
    public void paint(Graphics g) {
        for (Pelota_Contexto pelota : pelotas) {
            pelota.draw(g);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
