/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PracticaFlyweight;

import Contexto.Silla;
import FlyWeight.TipoSilla_FlyWeight;
import FlyWeight_Factory.Fabrica_SillaFlyWeight;
import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;

/**
 *
 * @author david
 */
public class MostrarSillas extends javax.swing.JFrame {

    private Fabrica_SillaFlyWeight fabrica = new Fabrica_SillaFlyWeight();
    private ArrayList<Silla> sillas = new ArrayList();
    /**
     * Creates new form PracticaFlyweight
     */
    public MostrarSillas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void mostrarSilla(int x, int y, String name, Color color, String descripcion) {
        TipoSilla_FlyWeight tipo_silla = Fabrica_SillaFlyWeight.getTipoSilla(name, color, descripcion);
        Silla silla = new Silla(x, y, tipo_silla);
        sillas.add(silla);
    }
    
    @Override
    public void paint(Graphics g){
        for(Silla silla: sillas){
            silla.draw(g);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
